[tool.poetry]
name = "parse-tg-bot"
version = "0.1.0"
description = ""
authors = ["Too Much Fun <mihail.karpinskii@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
